version: '3.9'

services:
  web:
    build:
      context: ./pointsApp
      dockerfile: Dockerfile
    ports:
      - "5001:5001"  # Ensure correct internal port mapping
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - web
      - database

  db:
    image: ghcr.io/eslih/postgres:16.1-alpine
    platform: linux/amd64  # or use another platform-specific image
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "myuser" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - database

networks:
  web:
  database:
